apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-deployment
  labels:
    app: receipt
  annotations:
    argocd-image-updater.argoproj.io/image-list: "703671902880.dkr.ecr.ap-northeast-2.amazonaws.com/dev-receipt"
    argocd-image-updater.argoproj.io/image-policy: "numerical"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: receipt
  template:
    metadata:
      labels:
        app: receipt
    spec:
      containers:
        - name: receipt-container
          image: 703671902880.dkr.ecr.ap-northeast-2.amazonaws.com/dev-receipt:9
          ports:
            - 8080
          resources:
            requests:
              cpu: "300m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
