apiVersion: v1
kind: Service
metadata:
  name: receipt-service
  labels:
    app: receipt
spec:
  selector:
    app: receipt
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP