apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-deployment
  labels:
    app: member
  annotations:
    argocd-image-updater.argoproj.io/image-list: "703671902880.dkr.ecr.ap-northeast-2.amazonaws.com/dev-member"
    argocd-image-updater.argoproj.io/image-policy: "numerical"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "app"
        effect: "NoSchedule"
      nodeSelector:
        node-group: app
      containers:
        - name: member-container
          image: 703671902880.dkr.ecr.ap-northeast-2.amazonaws.com/dev-member:30
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "300m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
