apiVersion: v1
kind: service
metadata:
  name: member-service
  labels:
    app: member
spec:
  selector:
    app: member
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP