apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  PORT: "8080"
  MEMBER-URL: "member-service.app.svc.cluster.local"
  AUCTION-URL: "auction-service.app.svc.cluster.local"
  RECEIPT-URL: "receipt-service.app.svc.cluster.local"