apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  PORT: "8080"
  MEMBER-URL: "member-service.app.svc.cluster.local"
  AUCTION-URL: "auction-service.app.svc.cluster.local"
  RECEIPT-URL: "receipt-service.app.svc.cluster.local"
  REDIS_HOST: "redis.lvwuks.ng.0001.apn2.cache.amazonaws.com:6379"
  DB_MEMBER_URL: "proxy-1732688014137-member.proxy-cxyu068w46fn.ap-northeast-2.rds.amazonaws.com"
  DB_AUCTION_URL: "proxy-1732688136161-auction.proxy-cxyu068w46fn.ap-northeast-2.rds.amazonaws.com"
  DB_RECEIPT_URL: "proxy-1732688217396-receipt.proxy-cxyu068w46fn.ap-northeast-2.rds.amazonaws.com"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  JWT_SECRET: "VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa"