apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: app
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_MEMBER_URL
      remoteRef:
        key: eks-secrets
        property: DB_MEMBER_URL
    - secretKey: DB_AUCTION_URL
      remoteRef:
        key: eks-secrets
        property: DB_AUCTION_URL
    - secretKey: DB_RECEIPT_URL
      remoteRef:
        key: eks-secrets
        property: DB_RECEIPT_URL
    - secretKey: DB_USERNAME
      remoteRef:
        key: eks-secrets
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: eks-secrets
        property: DB_PASSWORD
    - secretKey: REDIS_HOST
      remoteRef:
        key: eks-secrets
        property: REDIS_HOST
    - secretKey: JWT_SECRET
      remoteRef:
        key: eks-secrets
        property: JWT_SECRET