apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: app-taints
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: app-taints
  template:
    metadata:
      labels:
        app: app-taints
    spec:
      serviceAccountName: app-taints-sa
      containers:
      - name: add-taints
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          kubectl taint nodes ${NODE_NAME} dedicated=app:NoSchedule --overwrite
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube
          subPath: config
      volumes:
      - name: kubeconfig
        hostPath:
          path: /etc/kubernetes/admin.conf
          type: File
