apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-deployment
  labels:
    app: auction
  annotations:
    argocd-image-updater.argoproj.io/image-list: "703671902880.dkr.ecr.ap-northeast-2.amazonaws.com/dev-auction"
    argocd-image-updater.argoproj.io/image-policy: "numerical"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auction
  template:
    metadata:
      labels:
        app: auction
    spec:
      containers:
        - name: auction-container
          image: 703671902880.dkr.ecr.ap-northeast-2.amazonaws.com/dev-auction:21
          ports:
            - 8080
          resources:
            requests:
              cpu: "300m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
