apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auction-hpa
  labels:
    app: auction
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auction-deployment
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100
