apiVersion: v1
kind: service
metadata:
  name: auction-service
  labels:
    app: auction
spec:
  selector:
    app: auction
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP