apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-ebs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: <EBS_VOLUME_ID>
