apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiGateway-deployment
  labels:
    app: apiGateway
  annotations:
    argocd-image-updater.argoproj.io/image-list: "703671902880.dkr.ecr.ap-northeast-2.amazonaws.com/dev-apigateway"
    argocd-image-updater.argoproj.io/image-policy: "numerical"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apiGateway
  template:
    metadata:
      labels:
        app: apiGateway
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "app"
        effect: "NoSchedule"
      nodeSelector:
        node: app
      containers:
        - name: apiGateway-container
          image: 703671902880.dkr.ecr.ap-northeast-2.amazonaws.com/dev-apigateway:4
          ports:
            - 8080
          resources:
            requests:
              cpu: "300m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
