apiVersion: v1
kind: service
metadata:
  name: apiGateway-service
  labels:
    app: apiGateway
spec:
  selector:
    app: apiGateway
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP