resources:
  - ../../common
  - ../../services/member
  - ../../services/auction
  - ../../services/receipt
  - ../../services/apiGateway
  - namespace.yaml

namespace: prod

patchesStrategicMerge:
  - patch-ingress.yaml