apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    environment: prod
    node: app
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-node-selector
  namespace: app
spec:
  limits:
  - type: Pod
    defaultRequest:
      nodeSelector: "node=app"